### ISSUE TITLE
We should disallow issuing certificates for arbitrary keys

### ISSUE THREAD

**Issue by inahga** [peppelinux/draft-demarco-acme-openid-federation#24]
At minimum, we should avoid looking at the top level `jwks` field of the entity configuration for the requestor's key. OIDF states:

> These Federation Entity Keys SHOULD NOT be used in other protocols. (Keys to be used in other protocols, such as OpenID Connect, are conveyed in the metadata elements for the protocol's Entity Type Identifiers, such as the metadata under the openid_provider and openid_relying_party Entity Type Identifiers.)

I'm inclined to agree, since reusing cryptographic keys for different purposes is generally a bad idea. The issuer not reading the `jwks` field avoids the requestor misusing the entity key for another purpose.

Similarly, we should also probably not allow issuance for arbitrary keys in the entity metadata either. It would be better if we either defined a new Entity Type Identifier and metadata structure for the purpose of X.509 issuance, and/or allow the CA to define its metadata structures.

**Comment by peppelinux** [comment]
I fully agree to restrict x5c issuance to metadata jwks only and not federation entity keys.

For the second point we need further conversation during the editor's call
